"""Real-data integration tests for feature engineering (STEP_06).

Skips gracefully in clean CI runners lacking DVC panel data.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from src.features.builder import get_cuf_feature_names, get_derived_feature_names

PANEL_PATH = Path("data/processed/panel.parquet")
FEATURES_PATH = Path("data/processed/features.parquet")
MANIFEST_PATH = Path("reports/feature_manifest.json")


@pytest.fixture
def real_panel_and_features():
    """Load real panel and features if available on disk."""
    if not PANEL_PATH.exists():
        pytest.skip(f"Real panel not found at {PANEL_PATH} (DVC-tracked)")
    panel_df = pd.read_parquet(PANEL_PATH)

    features_df = None
    if FEATURES_PATH.exists():
        features_df = pd.read_parquet(FEATURES_PATH)

    return {"panel_df": panel_df, "features_df": features_df}


def test_real_feature_table_shape_and_alignment(real_panel_and_features):
    """Verify feature table has identical 18,860 rows and aligned keys with panel."""
    panel_df = real_panel_and_features["panel_df"]
    features_df = real_panel_and_features["features_df"]

    if features_df is None:
        from src.features.builder import compute_feature_table

        features_df, _ = compute_feature_table(panel_df)

    assert len(features_df) == len(panel_df) == 18860
    assert (features_df["project_id"] == panel_df["project_id"]).all()
    assert (features_df["report_month"] == panel_df["report_month"]).all()


def test_cuf_vs_derived_feature_counts(real_panel_and_features):
    """Verify feature set separation: 13 CUF features + 12 DERIVED features = 25 features."""
    cuf_cols = get_cuf_feature_names()
    derived_cols = get_derived_feature_names()

    assert len(cuf_cols) == 13
    assert len(derived_cols) == 12

    features_df = real_panel_and_features["features_df"]
    if features_df is None:
        from src.features.builder import compute_feature_table

        features_df, _ = compute_feature_table(real_panel_and_features["panel_df"])

    for col in cuf_cols:
        assert col in features_df.columns, f"Missing CUF feature: {col}"

    for col in derived_cols:
        assert col in features_df.columns, f"Missing DERIVED feature: {col}"


def test_no_infinite_values_in_features(real_panel_and_features):
    """Verify no inf/-inf values generated by division by zero in real data."""
    features_df = real_panel_and_features["features_df"]
    if features_df is None:
        from src.features.builder import compute_feature_table

        features_df, _ = compute_feature_table(real_panel_and_features["panel_df"])

    numeric_cols = features_df.select_dtypes(include=["number"]).columns
    for col in numeric_cols:
        inf_count = (~features_df[col].isin([float("inf"), float("-inf")])).all()
        assert inf_count, f"Infinite value found in feature column '{col}'"
