"""CI Ingestion & Parser Test Suite on Committed Synthetic Fixture.

This test suite runs in every CI environment (GitHub Actions, clean runners)
WITHOUT requiring external data, DVC pull, or Google Drive authentication.

It NEVER skips. If src/ingestion/parser.py suffers a regression, this test
turns CI RED immediately.

All expected values below are directly measured from:
    tests/fixtures/sample_flash_report.pdf
(generated by tests/fixtures/generate_fixture.py).
"""

from pathlib import Path

import pandas as pd
import pytest

from src.ingestion.parser import parse_flash_report

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "sample_flash_report.pdf"


@pytest.fixture(scope="module")
def fixture_data():
    """Parse the committed synthetic PDF fixture.

    Fails immediately if fixture is missing — NEVER calls pytest.skip().
    """
    assert (
        FIXTURE_PATH.exists()
    ), f"Required test fixture missing: {FIXTURE_PATH}. Run tests/fixtures/generate_fixture.py"
    return parse_flash_report(FIXTURE_PATH, source_month="2026-04")


def test_fixture_file_exists():
    """Verify that the committed PDF fixture is physically present in the repository."""
    assert FIXTURE_PATH.exists(), f"Fixture file not found at {FIXTURE_PATH}"
    assert FIXTURE_PATH.stat().st_size > 0, f"Fixture file {FIXTURE_PATH} is empty"


def test_table1_summary_extraction(fixture_data):
    """Verify Table 1 summary extraction against the fixture's printed summary page.

    Source values measured from Page 1 of tests/fixtures/sample_flash_report.pdf:
    - Printed 'Total' row: 1,981 projects, Rs 3,712,662.01 cr original, Rs 2,036,107.69 cr expenditure
    - Printed 'Ministry of Road Transport & Highways' row: 1,137 projects
    """
    t1 = fixture_data["table1_summary"]

    # Grand total project count printed in Table 1 Total row
    assert t1["table1_project_count"] == 1981, f"Expected 1981, got {t1['table1_project_count']}"

    # Cost and expenditure totals printed in Table 1 Total row
    assert (
        t1["table1_orig_cost_cr"] == 3712662.01
    ), f"Expected 3712662.01, got {t1['table1_orig_cost_cr']}"
    assert (
        t1["table1_cum_exp_cr"] == 2036107.69
    ), f"Expected 2036107.69, got {t1['table1_cum_exp_cr']}"

    # MoRTH count printed in Table 1 Road Transport row
    assert t1["morth_ongoing_count"] == 1137, f"Expected 1137, got {t1['morth_ongoing_count']}"


def test_ongoing_table_row_count_and_columns(fixture_data):
    """Verify Table 6 ongoing table row count and schema.

    Expected row count is exactly 3 (the measured number of ongoing project rows
    synthesized on Page 2 of tests/fixtures/sample_flash_report.pdf — NOT the
    full April report count of 1,981, which only runs in local/pre-merge validation).
    """
    df = fixture_data["ongoing"]
    assert isinstance(df, pd.DataFrame)
    assert len(df) == 3, f"Expected 3 rows in synthetic fixture, got {len(df)}"

    expected_cols = {
        "sl_no",
        "project_name",
        "implementing_agency",
        "project_code",
        "legacy_ocms_code",
        "pmgid",
        "ministry",
        "sector",
        "state",
        "date_of_approval",
        "start_date",
        "original_completion_date",
        "revised_completion_date",
        "original_cost_cr",
        "revised_cost_cr",
        "cumulative_expenditure_cr",
        "physical_progress_pct",
        "report_month",
        "source_doc",
    }
    assert expected_cols.issubset(
        set(df.columns)
    ), f"Missing columns: {expected_cols - set(df.columns)}"


def test_adversarial_paired_cost_splitting(fixture_data):
    """ADVERSARIAL ASSERTION: paired cost cells must split into distinct numeric columns.

    Source on Page 2 Row 1: '265.91\\n(280.50)'
    Must split into original_cost_cr=265.91 and revised_cost_cr=280.5.
    Must NOT remain merged as a string, nor contain parentheses.
    """
    df = fixture_data["ongoing"]
    row0 = df[df["sl_no"] == 1].iloc[0]

    # Values must be numeric floats
    assert isinstance(row0["original_cost_cr"], float)
    assert isinstance(row0["revised_cost_cr"], float)

    # Values measured from fixture
    assert row0["original_cost_cr"] == 265.91
    assert row0["revised_cost_cr"] == 280.50

    # Ensure they did not get conflated or merged
    assert row0["original_cost_cr"] != row0["revised_cost_cr"]

    # Fallback test: Page 2 Row 3 has only original cost '500.00' (no revised cost in source)
    row2 = df[df["sl_no"] == 3].iloc[0]
    assert row2["original_cost_cr"] == 500.00
    assert row2["revised_cost_cr"] == 500.00


def test_adversarial_null_token_normalization(fixture_data):
    """ADVERSARIAL ASSERTION: '-' and '(-)' placeholder tokens must parse to None/null.

    They must NEVER be preserved as literal string '-' or '(-)', which would corrupt
    downstream joins and key lookups.
    Source on Page 2 Row 2: legacy_ocms_code and pmgid are printed as '(-) (-)'
    Source on Page 2 Row 3: start_date and rev_doc are printed as '(-)'
    """
    df = fixture_data["ongoing"]
    row1 = df[df["sl_no"] == 2].iloc[0]

    # Must be None, NEVER the literal string '-'
    assert row1["legacy_ocms_code"] is None, f"Expected None, got {repr(row1['legacy_ocms_code'])}"
    assert row1["pmgid"] is None, f"Expected None, got {repr(row1['pmgid'])}"
    assert row1["legacy_ocms_code"] != "-"
    assert row1["pmgid"] != "-"

    row2 = df[df["sl_no"] == 3].iloc[0]
    assert row2["start_date"] is None, f"Expected None, got {repr(row2['start_date'])}"
    assert (
        row2["revised_completion_date"] is None
    ), f"Expected None, got {repr(row2['revised_completion_date'])}"
    assert row2["start_date"] != "-"
    assert row2["revised_completion_date"] != "-"


def test_garbage_cost_faithful_ingestion(fixture_data):
    """Verify that anomalous source values (revised_cost=0.1) are carried through faithfully.

    Source on Page 2 Row 2 (Project 618886):
    Original: 238.66, Revised: (0.1)
    The parser must faithfully ingest 0.1 rather than dropping or altering it.
    Validation flags belong in STEP_02, not STEP_01 ingestion.
    """
    df = fixture_data["ongoing"]
    row1 = df[df["sl_no"] == 2].iloc[0]

    assert row1["project_code"] == "618886"
    assert row1["original_cost_cr"] == 238.66
    assert row1["revised_cost_cr"] == 0.1


def test_paired_dates_and_multiline_project_name(fixture_data):
    """Verify paired date splitting and multi-line project name cleanup.

    Source on Page 2 Row 1:
    - Name lines: 'Construction of New Domestic Terminal Building' + 'and miscellaneous airside works'
    - Agency: '(AAI)'
    - Code: '(612786)'
    - Dates: '03/2023\\n(01/2024)' and '01/2026\\n(07/2026)'
    """
    df = fixture_data["ongoing"]
    row0 = df[df["sl_no"] == 1].iloc[0]

    expected_name = "Construction of New Domestic Terminal Building and miscellaneous airside works"
    assert row0["project_name"] == expected_name
    assert row0["implementing_agency"] == "AAI"
    assert row0["project_code"] == "612786"
    assert row0["legacy_ocms_code"] == "N04000106"
    assert row0["pmgid"] == "PMG12345"

    assert row0["date_of_approval"] == "03/2023"
    assert row0["start_date"] == "01/2024"
    assert row0["original_completion_date"] == "01/2026"
    assert row0["revised_completion_date"] == "07/2026"


def test_ministry_and_sector_forward_filling(fixture_data):
    """Verify that Ministry and Sector headers forward-fill onto all ongoing rows."""
    df = fixture_data["ongoing"]
    assert (df["ministry"] == "Ministry of Civil Aviation").all()
    assert (df["sector"] == "Civil Aviation").all()


def test_completed_and_newly_added_tables_extracted(fixture_data):
    """Verify that Table 3 (Completed) and Table 4 (Newly Added) are extracted from the fixture.

    Source values measured from Page 3 and Page 4:
    - Table 3 has 1 completed project: Project 701001 with actual completion 04/2026
    - Table 4 has 1 newly added project: Project 801001 with original cost 85.0
    """
    df_comp = fixture_data["completed"]
    df_new = fixture_data["newly_added"]

    assert len(df_comp) == 1, f"Expected 1 completed project, got {len(df_comp)}"
    row_comp = df_comp.iloc[0]
    assert row_comp["project_code"] == "701001"
    assert row_comp["actual_completion_date"] == "04/2026"
    assert row_comp["original_cost_cr"] == 150.0
    assert row_comp["revised_cost_cr"] == 165.0
    assert bool(row_comp["is_completed_this_month"]) is True

    assert len(df_new) == 1, f"Expected 1 newly added project, got {len(df_new)}"
    row_new = df_new.iloc[0]
    assert row_new["project_code"] == "801001"
    assert row_new["original_cost_cr"] == 85.0
    assert bool(row_new["is_newly_added_this_month"]) is True
